EXTERNAL playSound(happy)
EXTERNAL playSound(trevoga)
EXTERNAL playSound(pechal)
EXTERNAL playSound(soundName)
EXTERNAL playSound(soundName)
EXTERNAL playSound(soundName)
EXTERNAL playSound(soundName)